app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation

users:
    type:     rest
    resource: AppBundle\Controller\ProductController
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
